# Generated by Django 3.2.5 on 2021-07-20 20:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.IntegerField(verbose_name='Telegram ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ismi')),
                ('username', models.CharField(blank=True, max_length=32, null=True, verbose_name='Username')),
                ('telefon', models.CharField(blank=True, max_length=25, null=True, verbose_name='Telefon raqam')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Qo'shilgan vaqti")),
                ('account', models.IntegerField(default=0, verbose_name='Hisob')),
                ('step', models.IntegerField(default=0, verbose_name='---')),
            ],
        ),
    ]
