# Generated by Django 3.2.5 on 2021-07-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='englishword',
            name='true_word',
        ),
        migrations.RemoveField(
            model_name='englishword',
            name='word',
        ),
        migrations.AddField(
            model_name='englishword',
            name='en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ingliz'),
        ),
        migrations.AddField(
            model_name='englishword',
            name='uz',
            field=models.CharField(blank=True, max_length=100, verbose_name="O'zbek"),
        ),
    ]
